# Generated by Django 3.2.7 on 2021-09-23 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=2000)),
                ('front_banner', models.ImageField(upload_to='')),
                ('date_posted', models.DateField(default=datetime.datetime(2021, 9, 23, 18, 8, 7, 275135))),
            ],
        ),
    ]
