# Generated by Django 3.2.7 on 2021-09-23 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 9, 23, 18, 33, 19, 940309)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='front_banner',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
